//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LlamaLang.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LlamaLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
public interface ILlamaLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSourceFile([NotNull] LlamaLangParser.SourceFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierList([NotNull] LlamaLangParser.IdentifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] LlamaLangParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDecl([NotNull] LlamaLangParser.FunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] LlamaLangParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.varSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSpec([NotNull] LlamaLangParser.VarSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LlamaLangParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] LlamaLangParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LlamaLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.simpleStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleStmt([NotNull] LlamaLangParser.SimpleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.expressionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStmt([NotNull] LlamaLangParser.ExpressionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] LlamaLangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.assign_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_op([NotNull] LlamaLangParser.Assign_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.emptyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStmt([NotNull] LlamaLangParser.EmptyStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] LlamaLangParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_([NotNull] LlamaLangParser.Type_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer([NotNull] LlamaLangParser.PointerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] LlamaLangParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] LlamaLangParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignature([NotNull] LlamaLangParser.SignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] LlamaLangParser.ResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] LlamaLangParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.parameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDecl([NotNull] LlamaLangParser.ParameterDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] LlamaLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] LlamaLangParser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] LlamaLangParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversion([NotNull] LlamaLangParser.ConversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] LlamaLangParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOp([NotNull] LlamaLangParser.UnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] LlamaLangParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.basicLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasicLit([NotNull] LlamaLangParser.BasicLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] LlamaLangParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperandName([NotNull] LlamaLangParser.OperandNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdent([NotNull] LlamaLangParser.QualifiedIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.literalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralType([NotNull] LlamaLangParser.LiteralTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.fieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDecl([NotNull] LlamaLangParser.FieldDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_([NotNull] LlamaLangParser.String_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] LlamaLangParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.methodExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodExpr([NotNull] LlamaLangParser.MethodExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.receiverType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceiverType([NotNull] LlamaLangParser.ReceiverTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LlamaLangParser.eos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEos([NotNull] LlamaLangParser.EosContext context);
}
